/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/muyu.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.立方体.geometry}
        material={nodes.立方体.material}
        position={[-0.06, 0, -0.27]}
      />
    </group>
  );
}

useGLTF.preload('/muyu.glb');
